<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>io.github.swsk33</groupId>
		<artifactId>sql-initialize-parent</artifactId>
		<version>3.0.1</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>sql-initialize-test-parent</artifactId>
	<packaging>pom</packaging>
	<name>SQL-Initialize Test Parent</name>
	<description>SQL Initialize测试父项目</description>

	<modules>
		<module>sql-initialize-test-common</module>
		<module>sql-initialize-spring-boot2-test</module>
		<module>sql-initialize-spring-boot3-test</module>
		<module>sql-initialize-spring-boot4-test</module>
	</modules>

	<properties>
		<!-- 测试 Spring Boot 版本 -->
		<spring.boot2.test.version>2.7.18</spring.boot2.test.version>
		<spring.boot3.test.version>3.5.14</spring.boot3.test.version>
		<spring.boot4.test.version>4.0.5</spring.boot4.test.version>
		<!-- 覆盖 PostgreSQL 驱动版本 -->
		<postgre.version>42.7.11</postgre.version>
		<!-- 当前模块不进行发布 -->
		<skipPublishing>true</skipPublishing>
		<maven.deploy.skip>true</maven.deploy.skip>
	</properties>

	<dependencyManagement>
		<dependencies>
			<!-- SQL 初始化公用测试模块 -->
			<dependency>
				<groupId>io.github.swsk33</groupId>
				<artifactId>sql-initialize-test-common</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<!-- 统一 Spring Boot 插件配置 -->
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<version>${spring.boot2.test.version}</version>
					<executions>
						<execution>
							<goals>
								<goal>repackage</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<excludes>
							<exclude>
								<groupId>org.projectlombok</groupId>
								<artifactId>lombok</artifactId>
							</exclude>
						</excludes>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>